# Generated by Django 4.2.30 on 2026-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(choices=[('Run', 'Run'), ('Ride', 'Ride'), ('Swim', 'Swim'), ('Walk', 'Walk'), ('Hike', 'Hike'), ('Other', 'Other')], default='Other', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('distance_meters', models.FloatField(default=0)),
                ('moving_time_seconds', models.IntegerField(default=0)),
                ('elapsed_time_seconds', models.IntegerField(default=0)),
                ('total_elevation_gain', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('max_speed', models.FloatField(default=0)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('kudos_count', models.IntegerField(default=0)),
                ('trainer', models.BooleanField(default=False)),
                ('commute', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-start_date'],
            },
        ),
    ]
