# Generated by Django 4.2.30 on 2026-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stravatoken_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_cadence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
