# Generated by Django 6.0.5 on 2026-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_average_cadence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(choices=[('Run', 'Run'), ('Ride', 'Ride'), ('Swim', 'Swim'), ('Walk', 'Walk'), ('Hike', 'Hike'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
