# Generated by Django 6.0.5 on 2026-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_sport_type_alter_activity_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='achievement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
