# Generated by Django 4.2.30 on 2026-06-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_calories_achievement_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=255)),
                ('achievement_type', models.CharField(choices=[('pr', 'Personal Record'), ('kom', 'King of the Mountain'), ('cr', 'Course Record'), ('overall', 'Overall Leader')], default='pr', max_length=20)),
                ('rank', models.IntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_achievements', to='core.activity')),
            ],
            options={
                'ordering': ['achievement_type', 'segment_name'],
                'unique_together': {('activity', 'segment_name', 'achievement_type')},
            },
        ),
    ]
