# Generated by Django 4.2.30 on 2026-06-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_distance_m', models.IntegerField(help_text='Target distance in metres (e.g. 5000 for a 5-K window)')),
                ('elapsed_time_s', models.FloatField(help_text='Fastest elapsed time in seconds to cover the target distance')),
                ('achieved_at', models.DateField(help_text='Calendar date on which the activity took place')),
                ('pace_per_km', models.FloatField(help_text='Pace in decimal minutes per kilometre')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_efforts', to='core.activity')),
            ],
            options={
                'ordering': ['target_distance_m'],
                'unique_together': {('activity', 'target_distance_m')},
            },
        ),
    ]
